#
# ****Important**** Please read before adding your material/s 
# Add your Material title and URL to this list following the alphabetical order, as the theme doesn't accept random adding.
#
# 
title: Training materials
title_url: /training_materials
subitems:
  - title: RDMbites
    description: short informative videos (3_5 minutes) to describe basic and
      specialised aspects of RDM
    url: /rdmbites
    image_url: /assets/img/icons/rdmbites_icon.svg
    subitems:
      - title: Bioimage collection
        url: /bioimage_collection
      - title: Data management essentials collection
        url: /data_management_essentials_collection
      - title: Data Management Plans collection
        url: /dmp_collection
      - title: Equity, Diversity, Inclusion and Justice collection
        url: /edij_collection
      - title: Peatland data collection
        url: /peatland_data_collection
      - title: REDCap collection
        url: /redcap_collection
      - title: Sensitive data collection
        url: /sensitive_data_collection
      - title: Sequencing data collection
        url: /seq_data_collection
  - title: Course materials
    description: course materials open to the entire research community on basic and
      specialised aspects of RDM
    url: /course_materials
    image_url: /assets/img/icons/course_materials_icon.svg
    subitems:
      - title: Bioimage metadata course
        url: /bioimage_metadata_course
      - title: Coffee, Biscuits and Data
        url: /coffee_biscuits_data
      - title: ENA sequence submission
        url: /ena_submission_course
      - title: Equity, Diversity, Inclusion and Justice and data decolonisation
        url: /edij_data_decolonisation
      - title: FAIR data management for long-term agricultural experiments
        url: /fair_agricultural_course
      - title: FAIR data management solutions
        url: /fair_data_course
      - title: FAIR Galaxy Training Material
        url: /fair_gtn_course
      - title: FAIR in a nutshell course
        url: /fair_intro_course
      - title: FAIR Pointers course
        url: /fair_pointers_course
      - title: FAIRification of an RNAseq dataset
        url: /fairification_rnaseq_course
      - title: FAIRification of clinical datasets
        url: /fair_clinical_datasets_course
      - title: Introduction to cBioPortal
        url: /cbioportal-workshop
      - title: Managing and retrieving metagenomics data with MGnify
        url: /mgnify_course
      - title: RNA-Seq. Data Readiness for Machine Learning Applications
        url: /rna-seq-ml-course
  - title: Recommended resources
    description: curated list of recommended materials on RDM
    url: /recommended_resources
    image_url: /assets/img/icons/course_materials_icon.svg
