#-------------------------------
# Site Settings
title: ELIXIR-UK Fellowship
description: ELIXIR-UK Fellowship
logo: "/images/main-logo.png" # You can add own logo. For example "/images/logo.svg".
logo_dark: "/images/main-logo-dark.png"
funders: "/images/funders.png"
funders_dark: "/images/funders-dark.png"
partners: "/images/partners.png"
partners_dark: "/images/partners-dark.png"
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "Collections"
      url: "/collections/"
    - title: "Activities"
      url: "/activities/"
    - title: "Recommended resources"
      url: "/training_materials"
    - title: "Community"
      submenu:
      - url: "/fellows/"
        title: "Fellows"
      - url: "/mentors/"
        title: "Mentors"
      - url: "/coordination-team/"
        title: "Coordination Team"
      - url: "/collaborators/"
        title: "Collaborators"


# Call to action button
cta_button:
  enable: true
  cta_button_link: 'https://elixiruknode.org/activities/elixir-dash-fellowship'
  cta_button_text: Back to ELIXIR-UK


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: ELIXIR-UK Fellowship
  hero_description: Embedding RDM know-how into UK universities and institutes with a community of Data Stewardship Ambassadors


#-------------------------------
# Tags Section Settings
tags_section:
  enable: true
  number_posts: 3 # To control how many posts to show under each tag section, set the value to a number. Three is the default.
  number_columns: 3 # You can specify the number of columns from 1-4 for large screen resolution. By default, the theme uses three columns grid.
  tags:
    - tag: "RDMbites"
    - tag: "Courses"
    - tag: "Training delivery"

# You can add many tag sections to the homepage; each section will show the recent posts by the tag.


#-------------------------------
# Authors Section Settings
authors_section:
  enable: true
  section_title: Meet our Community


#-------------------------------
# Footer Settings
footer_description: This Fellowship was funded as part of the UKRI Innovation Scholars. Data Science Training in Health and Bioscience call (DaSH). (MR/V038966/1)

# Social Links
social:
- {icon: "twitter", link: "https://twitter.com/elixirnodeuk"}
- {icon: "linkedin", link: "https://www.linkedin.com/company/elixir-uk"}
- {icon: "youtube", link: "https://www.youtube.com/@elixir-uk"}

# Example of adding a new link to the footer - {icon: "instagram", link: "https://instagram.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Newsletter Settings
mailchimp_settings:
  enable: false
  mailchimp_title: Get interesting news
  mailchimp_description: Subscribe to our newsletter and we’ll send you the emails of latest posts.
  mailchimp_identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp_input_text: Your email address
  mailchimp_button_text: Subscribe


#-------------------------------
# Contact Settings
contact:
  email: contact@elixiruknode.org # Add your form_id
  description: Contact ELIXIR-UK for any queries about the Fellowship # Add a description of your form

# NOTE
# Danto theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
# disqus_identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id
